//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsScoringValidacionReglas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoringValidacionReglasDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoringValidacionReglasDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTipoScoringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsScoringValidacionReglas.ELDocumento oDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsScoringValidacionReglas.ELProducto oProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTipoScoring {
            get {
                return this.nTipoScoringField;
            }
            set {
                if ((object.ReferenceEquals(this.nTipoScoringField, value) != true)) {
                    this.nTipoScoringField = value;
                    this.RaisePropertyChanged("nTipoScoring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsScoringValidacionReglas.ELDocumento oDocumento {
            get {
                return this.oDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.oDocumentoField, value) != true)) {
                    this.oDocumentoField = value;
                    this.RaisePropertyChanged("oDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsScoringValidacionReglas.ELProducto oProducto {
            get {
                return this.oProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.oProductoField, value) != true)) {
                    this.oProductoField = value;
                    this.RaisePropertyChanged("oProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELDocumento", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNroDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTipoDoc {
            get {
                return this.nTipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.nTipoDocField, value) != true)) {
                    this.nTipoDocField = value;
                    this.RaisePropertyChanged("nTipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNroDoc {
            get {
                return this.sNroDocField;
            }
            set {
                if ((object.ReferenceEquals(this.sNroDocField, value) != true)) {
                    this.sNroDocField = value;
                    this.RaisePropertyChanged("sNroDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELProducto", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nModalidad {
            get {
                return this.nModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.nModalidadField, value) != true)) {
                    this.nModalidadField = value;
                    this.RaisePropertyChanged("nModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nProducto {
            get {
                return this.nProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.nProductoField, value) != true)) {
                    this.nProductoField = value;
                    this.RaisePropertyChanged("nProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoringValidacionReglasResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoringValidacionReglasResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nIdRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sDescRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nIdRechazo {
            get {
                return this.nIdRechazoField;
            }
            set {
                if ((this.nIdRechazoField.Equals(value) != true)) {
                    this.nIdRechazoField = value;
                    this.RaisePropertyChanged("nIdRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDescRechazo {
            get {
                return this.sDescRechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.sDescRechazoField, value) != true)) {
                    this.sDescRechazoField = value;
                    this.RaisePropertyChanged("sDescRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELClientePEPResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELClientePEPResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bEsPEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsScoringValidacionReglas.ELError oErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bEsPEP {
            get {
                return this.bEsPEPField;
            }
            set {
                if ((this.bEsPEPField.Equals(value) != true)) {
                    this.bEsPEPField = value;
                    this.RaisePropertyChanged("bEsPEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsScoringValidacionReglas.ELError oError {
            get {
                return this.oErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.oErrorField, value) != true)) {
                    this.oErrorField = value;
                    this.RaisePropertyChanged("oError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELError", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsScoringValidacionReglas.IwsScoringValidacionReglas")]
    public interface IwsScoringValidacionReglas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoringValidacionReglas/ScoringValidacionReglasRechazo", ReplyAction="http://tempuri.org/IwsScoringValidacionReglas/ScoringValidacionReglasRechazoRespo" +
            "nse")]
        TiboxWebApi.WebApi.wsScoringValidacionReglas.ELScoringValidacionReglasResultado ScoringValidacionReglasRechazo(TiboxWebApi.WebApi.wsScoringValidacionReglas.ELScoringValidacionReglasDatos poDatosValidacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoringValidacionReglas/ScoringValidacionReglasRechazo", ReplyAction="http://tempuri.org/IwsScoringValidacionReglas/ScoringValidacionReglasRechazoRespo" +
            "nse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoringValidacionReglas.ELScoringValidacionReglasResultado> ScoringValidacionReglasRechazoAsync(TiboxWebApi.WebApi.wsScoringValidacionReglas.ELScoringValidacionReglasDatos poDatosValidacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoringValidacionReglas/ValidaClientePEP", ReplyAction="http://tempuri.org/IwsScoringValidacionReglas/ValidaClientePEPResponse")]
        TiboxWebApi.WebApi.wsScoringValidacionReglas.ELClientePEPResultado ValidaClientePEP(TiboxWebApi.WebApi.wsScoringValidacionReglas.ELDocumento poDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoringValidacionReglas/ValidaClientePEP", ReplyAction="http://tempuri.org/IwsScoringValidacionReglas/ValidaClientePEPResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoringValidacionReglas.ELClientePEPResultado> ValidaClientePEPAsync(TiboxWebApi.WebApi.wsScoringValidacionReglas.ELDocumento poDatos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsScoringValidacionReglasChannel : TiboxWebApi.WebApi.wsScoringValidacionReglas.IwsScoringValidacionReglas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsScoringValidacionReglasClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsScoringValidacionReglas.IwsScoringValidacionReglas>, TiboxWebApi.WebApi.wsScoringValidacionReglas.IwsScoringValidacionReglas {
        
        public IwsScoringValidacionReglasClient() {
        }
        
        public IwsScoringValidacionReglasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsScoringValidacionReglasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoringValidacionReglasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoringValidacionReglasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TiboxWebApi.WebApi.wsScoringValidacionReglas.ELScoringValidacionReglasResultado ScoringValidacionReglasRechazo(TiboxWebApi.WebApi.wsScoringValidacionReglas.ELScoringValidacionReglasDatos poDatosValidacion) {
            return base.Channel.ScoringValidacionReglasRechazo(poDatosValidacion);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoringValidacionReglas.ELScoringValidacionReglasResultado> ScoringValidacionReglasRechazoAsync(TiboxWebApi.WebApi.wsScoringValidacionReglas.ELScoringValidacionReglasDatos poDatosValidacion) {
            return base.Channel.ScoringValidacionReglasRechazoAsync(poDatosValidacion);
        }
        
        public TiboxWebApi.WebApi.wsScoringValidacionReglas.ELClientePEPResultado ValidaClientePEP(TiboxWebApi.WebApi.wsScoringValidacionReglas.ELDocumento poDatos) {
            return base.Channel.ValidaClientePEP(poDatos);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoringValidacionReglas.ELClientePEPResultado> ValidaClientePEPAsync(TiboxWebApi.WebApi.wsScoringValidacionReglas.ELDocumento poDatos) {
            return base.Channel.ValidaClientePEPAsync(poDatos);
        }
    }
}
