//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsCPD {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELCPDMatrizDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELCPDMatrizDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nCodicionSituacionlaboralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nSitucionLaboralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTipoScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsCPD.ELProducto oProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nCodicionSituacionlaboral {
            get {
                return this.nCodicionSituacionlaboralField;
            }
            set {
                if ((object.ReferenceEquals(this.nCodicionSituacionlaboralField, value) != true)) {
                    this.nCodicionSituacionlaboralField = value;
                    this.RaisePropertyChanged("nCodicionSituacionlaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nSitucionLaboral {
            get {
                return this.nSitucionLaboralField;
            }
            set {
                if ((object.ReferenceEquals(this.nSitucionLaboralField, value) != true)) {
                    this.nSitucionLaboralField = value;
                    this.RaisePropertyChanged("nSitucionLaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTipoScore {
            get {
                return this.nTipoScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.nTipoScoreField, value) != true)) {
                    this.nTipoScoreField = value;
                    this.RaisePropertyChanged("nTipoScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsCPD.ELProducto oProducto {
            get {
                return this.oProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.oProductoField, value) != true)) {
                    this.oProductoField = value;
                    this.RaisePropertyChanged("oProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELProducto", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nModalidad {
            get {
                return this.nModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.nModalidadField, value) != true)) {
                    this.nModalidadField = value;
                    this.RaisePropertyChanged("nModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nProducto {
            get {
                return this.nProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.nProductoField, value) != true)) {
                    this.nProductoField = value;
                    this.RaisePropertyChanged("nProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELCPDMatrizResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELCPDMatrizResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bReqCPDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bReqCPD {
            get {
                return this.bReqCPDField;
            }
            set {
                if ((this.bReqCPDField.Equals(value) != true)) {
                    this.bReqCPDField = value;
                    this.RaisePropertyChanged("bReqCPD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCPD.IwsCPD")]
    public interface IwsCPD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsCPD/DevuelveRequiereCPD", ReplyAction="http://tempuri.org/IwsCPD/DevuelveRequiereCPDResponse")]
        TiboxWebApi.WebApi.wsCPD.ELCPDMatrizResultado DevuelveRequiereCPD(TiboxWebApi.WebApi.wsCPD.ELCPDMatrizDatos poDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsCPD/DevuelveRequiereCPD", ReplyAction="http://tempuri.org/IwsCPD/DevuelveRequiereCPDResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsCPD.ELCPDMatrizResultado> DevuelveRequiereCPDAsync(TiboxWebApi.WebApi.wsCPD.ELCPDMatrizDatos poDatos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsCPDChannel : TiboxWebApi.WebApi.wsCPD.IwsCPD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsCPDClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsCPD.IwsCPD>, TiboxWebApi.WebApi.wsCPD.IwsCPD {
        
        public IwsCPDClient() {
        }
        
        public IwsCPDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsCPDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsCPDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsCPDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TiboxWebApi.WebApi.wsCPD.ELCPDMatrizResultado DevuelveRequiereCPD(TiboxWebApi.WebApi.wsCPD.ELCPDMatrizDatos poDatos) {
            return base.Channel.DevuelveRequiereCPD(poDatos);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsCPD.ELCPDMatrizResultado> DevuelveRequiereCPDAsync(TiboxWebApi.WebApi.wsCPD.ELCPDMatrizDatos poDatos) {
            return base.Channel.DevuelveRequiereCPDAsync(poDatos);
        }
    }
}
