//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsPreAprobacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELDocumento", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNroDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTipoDoc {
            get {
                return this.nTipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.nTipoDocField, value) != true)) {
                    this.nTipoDocField = value;
                    this.RaisePropertyChanged("nTipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNroDoc {
            get {
                return this.sNroDocField;
            }
            set {
                if ((object.ReferenceEquals(this.sNroDocField, value) != true)) {
                    this.sNroDocField = value;
                    this.RaisePropertyChanged("sNroDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELProducto", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nModalidad {
            get {
                return this.nModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.nModalidadField, value) != true)) {
                    this.nModalidadField = value;
                    this.RaisePropertyChanged("nModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nProducto {
            get {
                return this.nProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.nProductoField, value) != true)) {
                    this.nProductoField = value;
                    this.RaisePropertyChanged("nProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELPreAprobacionResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELPreAprobacionResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cDecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cDescripcionRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cTipoScoringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nDecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPrestamoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPrestamoMinimoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cDecision {
            get {
                return this.cDecisionField;
            }
            set {
                if ((object.ReferenceEquals(this.cDecisionField, value) != true)) {
                    this.cDecisionField = value;
                    this.RaisePropertyChanged("cDecision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cDescripcionRechazo {
            get {
                return this.cDescripcionRechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.cDescripcionRechazoField, value) != true)) {
                    this.cDescripcionRechazoField = value;
                    this.RaisePropertyChanged("cDescripcionRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cTipoScoring {
            get {
                return this.cTipoScoringField;
            }
            set {
                if ((object.ReferenceEquals(this.cTipoScoringField, value) != true)) {
                    this.cTipoScoringField = value;
                    this.RaisePropertyChanged("cTipoScoring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nDecision {
            get {
                return this.nDecisionField;
            }
            set {
                if ((this.nDecisionField.Equals(value) != true)) {
                    this.nDecisionField = value;
                    this.RaisePropertyChanged("nDecision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPrestamoMaximo {
            get {
                return this.nPrestamoMaximoField;
            }
            set {
                if ((this.nPrestamoMaximoField.Equals(value) != true)) {
                    this.nPrestamoMaximoField = value;
                    this.RaisePropertyChanged("nPrestamoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPrestamoMinimo {
            get {
                return this.nPrestamoMinimoField;
            }
            set {
                if ((this.nPrestamoMinimoField.Equals(value) != true)) {
                    this.nPrestamoMinimoField = value;
                    this.RaisePropertyChanged("nPrestamoMinimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPreAprobacion.IwsPreAprobacion")]
    public interface IwsPreAprobacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPreAprobacion/DevuelvePreAprobacion", ReplyAction="http://tempuri.org/IwsPreAprobacion/DevuelvePreAprobacionResponse")]
        TiboxWebApi.WebApi.wsPreAprobacion.ELPreAprobacionResultado DevuelvePreAprobacion(TiboxWebApi.WebApi.wsPreAprobacion.ELDocumento poDatos, TiboxWebApi.WebApi.wsPreAprobacion.ELProducto poProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsPreAprobacion/DevuelvePreAprobacion", ReplyAction="http://tempuri.org/IwsPreAprobacion/DevuelvePreAprobacionResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsPreAprobacion.ELPreAprobacionResultado> DevuelvePreAprobacionAsync(TiboxWebApi.WebApi.wsPreAprobacion.ELDocumento poDatos, TiboxWebApi.WebApi.wsPreAprobacion.ELProducto poProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsPreAprobacionChannel : TiboxWebApi.WebApi.wsPreAprobacion.IwsPreAprobacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsPreAprobacionClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsPreAprobacion.IwsPreAprobacion>, TiboxWebApi.WebApi.wsPreAprobacion.IwsPreAprobacion {
        
        public IwsPreAprobacionClient() {
        }
        
        public IwsPreAprobacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsPreAprobacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPreAprobacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsPreAprobacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TiboxWebApi.WebApi.wsPreAprobacion.ELPreAprobacionResultado DevuelvePreAprobacion(TiboxWebApi.WebApi.wsPreAprobacion.ELDocumento poDatos, TiboxWebApi.WebApi.wsPreAprobacion.ELProducto poProducto) {
            return base.Channel.DevuelvePreAprobacion(poDatos, poProducto);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsPreAprobacion.ELPreAprobacionResultado> DevuelvePreAprobacionAsync(TiboxWebApi.WebApi.wsPreAprobacion.ELDocumento poDatos, TiboxWebApi.WebApi.wsPreAprobacion.ELProducto poProducto) {
            return base.Channel.DevuelvePreAprobacionAsync(poDatos, poProducto);
        }
    }
}
