//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsScoringDemografico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoringDemograficoDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoringDemograficoDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nGarantiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nIngresoPredecidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nModalidadLaboralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nMoraComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nScoreOtrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTipoFormalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsScoringDemografico.ELDocumento oDocumentoTitualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nGarantia {
            get {
                return this.nGarantiaField;
            }
            set {
                if ((object.ReferenceEquals(this.nGarantiaField, value) != true)) {
                    this.nGarantiaField = value;
                    this.RaisePropertyChanged("nGarantia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nIngresoPredecido {
            get {
                return this.nIngresoPredecidoField;
            }
            set {
                if ((object.ReferenceEquals(this.nIngresoPredecidoField, value) != true)) {
                    this.nIngresoPredecidoField = value;
                    this.RaisePropertyChanged("nIngresoPredecido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nModalidad {
            get {
                return this.nModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.nModalidadField, value) != true)) {
                    this.nModalidadField = value;
                    this.RaisePropertyChanged("nModalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nModalidadLaboral {
            get {
                return this.nModalidadLaboralField;
            }
            set {
                if ((object.ReferenceEquals(this.nModalidadLaboralField, value) != true)) {
                    this.nModalidadLaboralField = value;
                    this.RaisePropertyChanged("nModalidadLaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nMoraComercial {
            get {
                return this.nMoraComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.nMoraComercialField, value) != true)) {
                    this.nMoraComercialField = value;
                    this.RaisePropertyChanged("nMoraComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nProducto {
            get {
                return this.nProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.nProductoField, value) != true)) {
                    this.nProductoField = value;
                    this.RaisePropertyChanged("nProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nScore {
            get {
                return this.nScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.nScoreField, value) != true)) {
                    this.nScoreField = value;
                    this.RaisePropertyChanged("nScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nScoreOtros {
            get {
                return this.nScoreOtrosField;
            }
            set {
                if ((object.ReferenceEquals(this.nScoreOtrosField, value) != true)) {
                    this.nScoreOtrosField = value;
                    this.RaisePropertyChanged("nScoreOtros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTipoFormalidad {
            get {
                return this.nTipoFormalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.nTipoFormalidadField, value) != true)) {
                    this.nTipoFormalidadField = value;
                    this.RaisePropertyChanged("nTipoFormalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsScoringDemografico.ELDocumento oDocumentoTitual {
            get {
                return this.oDocumentoTitualField;
            }
            set {
                if ((object.ReferenceEquals(this.oDocumentoTitualField, value) != true)) {
                    this.oDocumentoTitualField = value;
                    this.RaisePropertyChanged("oDocumentoTitual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELDocumento", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNroDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTipoDoc {
            get {
                return this.nTipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.nTipoDocField, value) != true)) {
                    this.nTipoDocField = value;
                    this.RaisePropertyChanged("nTipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNroDoc {
            get {
                return this.sNroDocField;
            }
            set {
                if ((object.ReferenceEquals(this.sNroDocField, value) != true)) {
                    this.sNroDocField = value;
                    this.RaisePropertyChanged("sNroDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoringDemograficoResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoringDemograficoResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nCuotaDisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nCuotaMaximaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nCuotaUtilizadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nDecicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPlazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPorcGarantiaAvaluoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPorcentajeInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPrestamo1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPrestamo2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPrestamo3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPrestamo4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPrestamoMaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nPrestamoMinimoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nRCIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nRMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nTasaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sDescripcionRechazoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nCategoria {
            get {
                return this.nCategoriaField;
            }
            set {
                if ((this.nCategoriaField.Equals(value) != true)) {
                    this.nCategoriaField = value;
                    this.RaisePropertyChanged("nCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nCuotaDisponible {
            get {
                return this.nCuotaDisponibleField;
            }
            set {
                if ((this.nCuotaDisponibleField.Equals(value) != true)) {
                    this.nCuotaDisponibleField = value;
                    this.RaisePropertyChanged("nCuotaDisponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nCuotaMaxima {
            get {
                return this.nCuotaMaximaField;
            }
            set {
                if ((this.nCuotaMaximaField.Equals(value) != true)) {
                    this.nCuotaMaximaField = value;
                    this.RaisePropertyChanged("nCuotaMaxima");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nCuotaUtilizada {
            get {
                return this.nCuotaUtilizadaField;
            }
            set {
                if ((this.nCuotaUtilizadaField.Equals(value) != true)) {
                    this.nCuotaUtilizadaField = value;
                    this.RaisePropertyChanged("nCuotaUtilizada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nDecicion {
            get {
                return this.nDecicionField;
            }
            set {
                if ((this.nDecicionField.Equals(value) != true)) {
                    this.nDecicionField = value;
                    this.RaisePropertyChanged("nDecicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPlazo {
            get {
                return this.nPlazoField;
            }
            set {
                if ((this.nPlazoField.Equals(value) != true)) {
                    this.nPlazoField = value;
                    this.RaisePropertyChanged("nPlazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPorcGarantiaAvaluo {
            get {
                return this.nPorcGarantiaAvaluoField;
            }
            set {
                if ((this.nPorcGarantiaAvaluoField.Equals(value) != true)) {
                    this.nPorcGarantiaAvaluoField = value;
                    this.RaisePropertyChanged("nPorcGarantiaAvaluo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPorcentajeInicial {
            get {
                return this.nPorcentajeInicialField;
            }
            set {
                if ((this.nPorcentajeInicialField.Equals(value) != true)) {
                    this.nPorcentajeInicialField = value;
                    this.RaisePropertyChanged("nPorcentajeInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPrestamo1 {
            get {
                return this.nPrestamo1Field;
            }
            set {
                if ((this.nPrestamo1Field.Equals(value) != true)) {
                    this.nPrestamo1Field = value;
                    this.RaisePropertyChanged("nPrestamo1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPrestamo2 {
            get {
                return this.nPrestamo2Field;
            }
            set {
                if ((this.nPrestamo2Field.Equals(value) != true)) {
                    this.nPrestamo2Field = value;
                    this.RaisePropertyChanged("nPrestamo2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPrestamo3 {
            get {
                return this.nPrestamo3Field;
            }
            set {
                if ((this.nPrestamo3Field.Equals(value) != true)) {
                    this.nPrestamo3Field = value;
                    this.RaisePropertyChanged("nPrestamo3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPrestamo4 {
            get {
                return this.nPrestamo4Field;
            }
            set {
                if ((this.nPrestamo4Field.Equals(value) != true)) {
                    this.nPrestamo4Field = value;
                    this.RaisePropertyChanged("nPrestamo4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPrestamoMaximo {
            get {
                return this.nPrestamoMaximoField;
            }
            set {
                if ((this.nPrestamoMaximoField.Equals(value) != true)) {
                    this.nPrestamoMaximoField = value;
                    this.RaisePropertyChanged("nPrestamoMaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nPrestamoMinimo {
            get {
                return this.nPrestamoMinimoField;
            }
            set {
                if ((this.nPrestamoMinimoField.Equals(value) != true)) {
                    this.nPrestamoMinimoField = value;
                    this.RaisePropertyChanged("nPrestamoMinimo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nRCI {
            get {
                return this.nRCIField;
            }
            set {
                if ((this.nRCIField.Equals(value) != true)) {
                    this.nRCIField = value;
                    this.RaisePropertyChanged("nRCI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nRMA {
            get {
                return this.nRMAField;
            }
            set {
                if ((this.nRMAField.Equals(value) != true)) {
                    this.nRMAField = value;
                    this.RaisePropertyChanged("nRMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nTasa {
            get {
                return this.nTasaField;
            }
            set {
                if ((this.nTasaField.Equals(value) != true)) {
                    this.nTasaField = value;
                    this.RaisePropertyChanged("nTasa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sDescripcionRechazo {
            get {
                return this.sDescripcionRechazoField;
            }
            set {
                if ((object.ReferenceEquals(this.sDescripcionRechazoField, value) != true)) {
                    this.sDescripcionRechazoField = value;
                    this.RaisePropertyChanged("sDescripcionRechazo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsScoringDemografico.IwsScoringDemografico")]
    public interface IwsScoringDemografico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoringDemografico/ScoringDemografico", ReplyAction="http://tempuri.org/IwsScoringDemografico/ScoringDemograficoResponse")]
        TiboxWebApi.WebApi.wsScoringDemografico.ELScoringDemograficoResultado ScoringDemografico(TiboxWebApi.WebApi.wsScoringDemografico.ELScoringDemograficoDatos poDatosScoring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoringDemografico/ScoringDemografico", ReplyAction="http://tempuri.org/IwsScoringDemografico/ScoringDemograficoResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoringDemografico.ELScoringDemograficoResultado> ScoringDemograficoAsync(TiboxWebApi.WebApi.wsScoringDemografico.ELScoringDemograficoDatos poDatosScoring);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsScoringDemograficoChannel : TiboxWebApi.WebApi.wsScoringDemografico.IwsScoringDemografico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsScoringDemograficoClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsScoringDemografico.IwsScoringDemografico>, TiboxWebApi.WebApi.wsScoringDemografico.IwsScoringDemografico {
        
        public IwsScoringDemograficoClient() {
        }
        
        public IwsScoringDemograficoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsScoringDemograficoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoringDemograficoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoringDemograficoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TiboxWebApi.WebApi.wsScoringDemografico.ELScoringDemograficoResultado ScoringDemografico(TiboxWebApi.WebApi.wsScoringDemografico.ELScoringDemograficoDatos poDatosScoring) {
            return base.Channel.ScoringDemografico(poDatosScoring);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoringDemografico.ELScoringDemograficoResultado> ScoringDemograficoAsync(TiboxWebApi.WebApi.wsScoringDemografico.ELScoringDemograficoDatos poDatosScoring) {
            return base.Channel.ScoringDemograficoAsync(poDatosScoring);
        }
    }
}
