//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsScoreBuro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoreBuroDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoreBuroDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNroDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNroDoc {
            get {
                return this.sNroDocField;
            }
            set {
                if ((object.ReferenceEquals(this.sNroDocField, value) != true)) {
                    this.sNroDocField = value;
                    this.RaisePropertyChanged("sNroDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoreBuroResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoreBuroResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nScoreBuroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nScoreBuro {
            get {
                return this.nScoreBuroField;
            }
            set {
                if ((this.nScoreBuroField.Equals(value) != true)) {
                    this.nScoreBuroField = value;
                    this.RaisePropertyChanged("nScoreBuro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsScoreBuro.IwsScoreBuro")]
    public interface IwsScoreBuro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoreBuro/ScoreBuro", ReplyAction="http://tempuri.org/IwsScoreBuro/ScoreBuroResponse")]
        TiboxWebApi.WebApi.wsScoreBuro.ELScoreBuroResultado ScoreBuro(TiboxWebApi.WebApi.wsScoreBuro.ELScoreBuroDatos poDatosScore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoreBuro/ScoreBuro", ReplyAction="http://tempuri.org/IwsScoreBuro/ScoreBuroResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoreBuro.ELScoreBuroResultado> ScoreBuroAsync(TiboxWebApi.WebApi.wsScoreBuro.ELScoreBuroDatos poDatosScore);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsScoreBuroChannel : TiboxWebApi.WebApi.wsScoreBuro.IwsScoreBuro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsScoreBuroClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsScoreBuro.IwsScoreBuro>, TiboxWebApi.WebApi.wsScoreBuro.IwsScoreBuro {
        
        public IwsScoreBuroClient() {
        }
        
        public IwsScoreBuroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsScoreBuroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoreBuroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoreBuroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TiboxWebApi.WebApi.wsScoreBuro.ELScoreBuroResultado ScoreBuro(TiboxWebApi.WebApi.wsScoreBuro.ELScoreBuroDatos poDatosScore) {
            return base.Channel.ScoreBuro(poDatosScore);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoreBuro.ELScoreBuroResultado> ScoreBuroAsync(TiboxWebApi.WebApi.wsScoreBuro.ELScoreBuroDatos poDatosScore) {
            return base.Channel.ScoreBuroAsync(poDatosScore);
        }
    }
}
