//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsIngresoPredecido {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELIngresoPredecidoDemograficoDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELIngresoPredecidoDemograficoDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nConstanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nEdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nEstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nGeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCIIUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sUbiGeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nConstante {
            get {
                return this.nConstanteField;
            }
            set {
                if ((object.ReferenceEquals(this.nConstanteField, value) != true)) {
                    this.nConstanteField = value;
                    this.RaisePropertyChanged("nConstante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nEdad {
            get {
                return this.nEdadField;
            }
            set {
                if ((object.ReferenceEquals(this.nEdadField, value) != true)) {
                    this.nEdadField = value;
                    this.RaisePropertyChanged("nEdad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nEstadoCivil {
            get {
                return this.nEstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.nEstadoCivilField, value) != true)) {
                    this.nEstadoCivilField = value;
                    this.RaisePropertyChanged("nEstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nGenero {
            get {
                return this.nGeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.nGeneroField, value) != true)) {
                    this.nGeneroField = value;
                    this.RaisePropertyChanged("nGenero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCIIU {
            get {
                return this.sCIIUField;
            }
            set {
                if ((object.ReferenceEquals(this.sCIIUField, value) != true)) {
                    this.sCIIUField = value;
                    this.RaisePropertyChanged("sCIIU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sUbiGeo {
            get {
                return this.sUbiGeoField;
            }
            set {
                if ((object.ReferenceEquals(this.sUbiGeoField, value) != true)) {
                    this.sUbiGeoField = value;
                    this.RaisePropertyChanged("sUbiGeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELIngresoPredecidoDemograficoResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELIngresoPredecidoDemograficoResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsIngresoPredecido.PuntajeIPDItems[] PuntajeIPDItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nIngresoPredecidoDemografico1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nIngresoPredecidoDemografico2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nIngresoPredecidoDemografico3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsIngresoPredecido.PuntajeIPDItems[] PuntajeIPDItems {
            get {
                return this.PuntajeIPDItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntajeIPDItemsField, value) != true)) {
                    this.PuntajeIPDItemsField = value;
                    this.RaisePropertyChanged("PuntajeIPDItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nIngresoPredecidoDemografico1 {
            get {
                return this.nIngresoPredecidoDemografico1Field;
            }
            set {
                if ((this.nIngresoPredecidoDemografico1Field.Equals(value) != true)) {
                    this.nIngresoPredecidoDemografico1Field = value;
                    this.RaisePropertyChanged("nIngresoPredecidoDemografico1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nIngresoPredecidoDemografico2 {
            get {
                return this.nIngresoPredecidoDemografico2Field;
            }
            set {
                if ((this.nIngresoPredecidoDemografico2Field.Equals(value) != true)) {
                    this.nIngresoPredecidoDemografico2Field = value;
                    this.RaisePropertyChanged("nIngresoPredecidoDemografico2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nIngresoPredecidoDemografico3 {
            get {
                return this.nIngresoPredecidoDemografico3Field;
            }
            set {
                if ((this.nIngresoPredecidoDemografico3Field.Equals(value) != true)) {
                    this.nIngresoPredecidoDemografico3Field = value;
                    this.RaisePropertyChanged("nIngresoPredecidoDemografico3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PuntajeIPDItems", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class PuntajeIPDItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nVariablePuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sVariableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sVariableDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nVariablePuntaje {
            get {
                return this.nVariablePuntajeField;
            }
            set {
                if ((this.nVariablePuntajeField.Equals(value) != true)) {
                    this.nVariablePuntajeField = value;
                    this.RaisePropertyChanged("nVariablePuntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sVariable {
            get {
                return this.sVariableField;
            }
            set {
                if ((object.ReferenceEquals(this.sVariableField, value) != true)) {
                    this.sVariableField = value;
                    this.RaisePropertyChanged("sVariable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sVariableDescripcion {
            get {
                return this.sVariableDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.sVariableDescripcionField, value) != true)) {
                    this.sVariableDescripcionField = value;
                    this.RaisePropertyChanged("sVariableDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELIngresoPredecidoRCCDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELIngresoPredecidoRCCDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nEstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsIngresoPredecido.ELDocumento oDocumentoConyugeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsIngresoPredecido.ELDocumento oDocumentoTitularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nEstadoCivil {
            get {
                return this.nEstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.nEstadoCivilField, value) != true)) {
                    this.nEstadoCivilField = value;
                    this.RaisePropertyChanged("nEstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELDocumento oDocumentoConyuge {
            get {
                return this.oDocumentoConyugeField;
            }
            set {
                if ((object.ReferenceEquals(this.oDocumentoConyugeField, value) != true)) {
                    this.oDocumentoConyugeField = value;
                    this.RaisePropertyChanged("oDocumentoConyuge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELDocumento oDocumentoTitular {
            get {
                return this.oDocumentoTitularField;
            }
            set {
                if ((object.ReferenceEquals(this.oDocumentoTitularField, value) != true)) {
                    this.oDocumentoTitularField = value;
                    this.RaisePropertyChanged("oDocumentoTitular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELDocumento", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNroDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTipoDoc {
            get {
                return this.nTipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.nTipoDocField, value) != true)) {
                    this.nTipoDocField = value;
                    this.RaisePropertyChanged("nTipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNroDoc {
            get {
                return this.sNroDocField;
            }
            set {
                if ((object.ReferenceEquals(this.sNroDocField, value) != true)) {
                    this.sNroDocField = value;
                    this.RaisePropertyChanged("sNroDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELIngresoPredecidoRCCResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELIngresoPredecidoRCCResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsIngresoPredecido.DeudaRCCItems[] DeudasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nIngresoPredecidoRCC1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nIngresoPredecidoRCC2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nIngresoPredecidoRCC3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsIngresoPredecido.DeudaRCCItems[] Deudas {
            get {
                return this.DeudasField;
            }
            set {
                if ((object.ReferenceEquals(this.DeudasField, value) != true)) {
                    this.DeudasField = value;
                    this.RaisePropertyChanged("Deudas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nIngresoPredecidoRCC1 {
            get {
                return this.nIngresoPredecidoRCC1Field;
            }
            set {
                if ((this.nIngresoPredecidoRCC1Field.Equals(value) != true)) {
                    this.nIngresoPredecidoRCC1Field = value;
                    this.RaisePropertyChanged("nIngresoPredecidoRCC1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nIngresoPredecidoRCC2 {
            get {
                return this.nIngresoPredecidoRCC2Field;
            }
            set {
                if ((this.nIngresoPredecidoRCC2Field.Equals(value) != true)) {
                    this.nIngresoPredecidoRCC2Field = value;
                    this.RaisePropertyChanged("nIngresoPredecidoRCC2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nIngresoPredecidoRCC3 {
            get {
                return this.nIngresoPredecidoRCC3Field;
            }
            set {
                if ((this.nIngresoPredecidoRCC3Field.Equals(value) != true)) {
                    this.nIngresoPredecidoRCC3Field = value;
                    this.RaisePropertyChanged("nIngresoPredecidoRCC3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeudaRCCItems", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class DeudaRCCItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nFactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nInferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nMontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nTipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sCaracteristicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sTipoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nFactor {
            get {
                return this.nFactorField;
            }
            set {
                if ((this.nFactorField.Equals(value) != true)) {
                    this.nFactorField = value;
                    this.RaisePropertyChanged("nFactor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nInferencia {
            get {
                return this.nInferenciaField;
            }
            set {
                if ((this.nInferenciaField.Equals(value) != true)) {
                    this.nInferenciaField = value;
                    this.RaisePropertyChanged("nInferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nMonto {
            get {
                return this.nMontoField;
            }
            set {
                if ((this.nMontoField.Equals(value) != true)) {
                    this.nMontoField = value;
                    this.RaisePropertyChanged("nMonto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nTipoId {
            get {
                return this.nTipoIdField;
            }
            set {
                if ((this.nTipoIdField.Equals(value) != true)) {
                    this.nTipoIdField = value;
                    this.RaisePropertyChanged("nTipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sCaracteristica {
            get {
                return this.sCaracteristicaField;
            }
            set {
                if ((object.ReferenceEquals(this.sCaracteristicaField, value) != true)) {
                    this.sCaracteristicaField = value;
                    this.RaisePropertyChanged("sCaracteristica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sTipoDescripcion {
            get {
                return this.sTipoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.sTipoDescripcionField, value) != true)) {
                    this.sTipoDescripcionField = value;
                    this.RaisePropertyChanged("sTipoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELIngresoPredecidoDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELIngresoPredecidoDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nIngresoPredecidoDemograficoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nIngresoPredecidoRCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoDatos oDatosDemograficoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCDatos oDatosRCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsIngresoPredecido.ELDocumento oDocumentoTitularField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nIngresoPredecidoDemografico {
            get {
                return this.nIngresoPredecidoDemograficoField;
            }
            set {
                if ((object.ReferenceEquals(this.nIngresoPredecidoDemograficoField, value) != true)) {
                    this.nIngresoPredecidoDemograficoField = value;
                    this.RaisePropertyChanged("nIngresoPredecidoDemografico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nIngresoPredecidoRCC {
            get {
                return this.nIngresoPredecidoRCCField;
            }
            set {
                if ((object.ReferenceEquals(this.nIngresoPredecidoRCCField, value) != true)) {
                    this.nIngresoPredecidoRCCField = value;
                    this.RaisePropertyChanged("nIngresoPredecidoRCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoDatos oDatosDemografico {
            get {
                return this.oDatosDemograficoField;
            }
            set {
                if ((object.ReferenceEquals(this.oDatosDemograficoField, value) != true)) {
                    this.oDatosDemograficoField = value;
                    this.RaisePropertyChanged("oDatosDemografico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCDatos oDatosRCC {
            get {
                return this.oDatosRCCField;
            }
            set {
                if ((object.ReferenceEquals(this.oDatosRCCField, value) != true)) {
                    this.oDatosRCCField = value;
                    this.RaisePropertyChanged("oDatosRCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELDocumento oDocumentoTitular {
            get {
                return this.oDocumentoTitularField;
            }
            set {
                if ((object.ReferenceEquals(this.oDocumentoTitularField, value) != true)) {
                    this.oDocumentoTitularField = value;
                    this.RaisePropertyChanged("oDocumentoTitular");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELIngresoPredecidoResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELIngresoPredecidoResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nIngresoPredecidoFinal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nIngresoPredecidoFinal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nIngresoPredecidoFinal1 {
            get {
                return this.nIngresoPredecidoFinal1Field;
            }
            set {
                if ((this.nIngresoPredecidoFinal1Field.Equals(value) != true)) {
                    this.nIngresoPredecidoFinal1Field = value;
                    this.RaisePropertyChanged("nIngresoPredecidoFinal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nIngresoPredecidoFinal2 {
            get {
                return this.nIngresoPredecidoFinal2Field;
            }
            set {
                if ((this.nIngresoPredecidoFinal2Field.Equals(value) != true)) {
                    this.nIngresoPredecidoFinal2Field = value;
                    this.RaisePropertyChanged("nIngresoPredecidoFinal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELIngresoCliente", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELIngresoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nIngresoDeclaradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nIngresoFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nIngresoPredecidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsIngresoPredecido.ELError oErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nIngresoDeclarado {
            get {
                return this.nIngresoDeclaradoField;
            }
            set {
                if ((object.ReferenceEquals(this.nIngresoDeclaradoField, value) != true)) {
                    this.nIngresoDeclaradoField = value;
                    this.RaisePropertyChanged("nIngresoDeclarado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nIngresoFinal {
            get {
                return this.nIngresoFinalField;
            }
            set {
                if ((object.ReferenceEquals(this.nIngresoFinalField, value) != true)) {
                    this.nIngresoFinalField = value;
                    this.RaisePropertyChanged("nIngresoFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nIngresoPredecido {
            get {
                return this.nIngresoPredecidoField;
            }
            set {
                if ((object.ReferenceEquals(this.nIngresoPredecidoField, value) != true)) {
                    this.nIngresoPredecidoField = value;
                    this.RaisePropertyChanged("nIngresoPredecido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELError oError {
            get {
                return this.oErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.oErrorField, value) != true)) {
                    this.oErrorField = value;
                    this.RaisePropertyChanged("oError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELError", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsIngresoPredecido.IngresoPredecido")]
    public interface IngresoPredecido {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresoPredecido/IngresoPredecidoDemografico", ReplyAction="http://tempuri.org/IngresoPredecido/IngresoPredecidoDemograficoResponse")]
        TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoResultado IngresoPredecidoDemografico(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoDatos poDatosIngresoPredecido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresoPredecido/IngresoPredecidoDemografico", ReplyAction="http://tempuri.org/IngresoPredecido/IngresoPredecidoDemograficoResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoResultado> IngresoPredecidoDemograficoAsync(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoDatos poDatosIngresoPredecido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresoPredecido/IngresoPredecidoRCC", ReplyAction="http://tempuri.org/IngresoPredecido/IngresoPredecidoRCCResponse")]
        TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCResultado IngresoPredecidoRCC(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCDatos poDatosIngresoPredecido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresoPredecido/IngresoPredecidoRCC", ReplyAction="http://tempuri.org/IngresoPredecido/IngresoPredecidoRCCResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCResultado> IngresoPredecidoRCCAsync(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCDatos poDatosIngresoPredecido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresoPredecido/IngresoPredecido", ReplyAction="http://tempuri.org/IngresoPredecido/IngresoPredecidoResponse")]
        TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoResultado IngresoPredecido(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDatos poDatosIngresoPredecido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresoPredecido/IngresoPredecido", ReplyAction="http://tempuri.org/IngresoPredecido/IngresoPredecidoResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoResultado> IngresoPredecidoAsync(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDatos poDatosIngresoPredecido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresoPredecido/IngresoPredecidoVsIngresoDeclarado", ReplyAction="http://tempuri.org/IngresoPredecido/IngresoPredecidoVsIngresoDeclaradoResponse")]
        TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoCliente IngresoPredecidoVsIngresoDeclarado(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoCliente poDatoIngresos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IngresoPredecido/IngresoPredecidoVsIngresoDeclarado", ReplyAction="http://tempuri.org/IngresoPredecido/IngresoPredecidoVsIngresoDeclaradoResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoCliente> IngresoPredecidoVsIngresoDeclaradoAsync(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoCliente poDatoIngresos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IngresoPredecidoChannel : TiboxWebApi.WebApi.wsIngresoPredecido.IngresoPredecido, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngresoPredecidoClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsIngresoPredecido.IngresoPredecido>, TiboxWebApi.WebApi.wsIngresoPredecido.IngresoPredecido {
        
        public IngresoPredecidoClient() {
        }
        
        public IngresoPredecidoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngresoPredecidoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresoPredecidoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngresoPredecidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoResultado IngresoPredecidoDemografico(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoDatos poDatosIngresoPredecido) {
            return base.Channel.IngresoPredecidoDemografico(poDatosIngresoPredecido);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoResultado> IngresoPredecidoDemograficoAsync(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDemograficoDatos poDatosIngresoPredecido) {
            return base.Channel.IngresoPredecidoDemograficoAsync(poDatosIngresoPredecido);
        }
        
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCResultado IngresoPredecidoRCC(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCDatos poDatosIngresoPredecido) {
            return base.Channel.IngresoPredecidoRCC(poDatosIngresoPredecido);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCResultado> IngresoPredecidoRCCAsync(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoRCCDatos poDatosIngresoPredecido) {
            return base.Channel.IngresoPredecidoRCCAsync(poDatosIngresoPredecido);
        }
        
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoResultado IngresoPredecido(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDatos poDatosIngresoPredecido) {
            return base.Channel.IngresoPredecido(poDatosIngresoPredecido);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoResultado> IngresoPredecidoAsync(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoPredecidoDatos poDatosIngresoPredecido) {
            return base.Channel.IngresoPredecidoAsync(poDatosIngresoPredecido);
        }
        
        public TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoCliente IngresoPredecidoVsIngresoDeclarado(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoCliente poDatoIngresos) {
            return base.Channel.IngresoPredecidoVsIngresoDeclarado(poDatoIngresos);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoCliente> IngresoPredecidoVsIngresoDeclaradoAsync(TiboxWebApi.WebApi.wsIngresoPredecido.ELIngresoCliente poDatoIngresos) {
            return base.Channel.IngresoPredecidoVsIngresoDeclaradoAsync(poDatoIngresos);
        }
    }
}
