//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsScoreComportamiento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoreComportamientoDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoreComportamientoDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nCodPersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nCodPers {
            get {
                return this.nCodPersField;
            }
            set {
                if ((object.ReferenceEquals(this.nCodPersField, value) != true)) {
                    this.nCodPersField = value;
                    this.RaisePropertyChanged("nCodPers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nProducto {
            get {
                return this.nProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.nProductoField, value) != true)) {
                    this.nProductoField = value;
                    this.RaisePropertyChanged("nProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoreComportamientoResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoreComportamientoResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double nScoreComportamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double nScoreComportamiento {
            get {
                return this.nScoreComportamientoField;
            }
            set {
                if ((this.nScoreComportamientoField.Equals(value) != true)) {
                    this.nScoreComportamientoField = value;
                    this.RaisePropertyChanged("nScoreComportamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsScoreComportamiento.IwsScoreComportamiento")]
    public interface IwsScoreComportamiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoreComportamiento/DevuelveScoreComportamiento", ReplyAction="http://tempuri.org/IwsScoreComportamiento/DevuelveScoreComportamientoResponse")]
        TiboxWebApi.WebApi.wsScoreComportamiento.ELScoreComportamientoResultado DevuelveScoreComportamiento(TiboxWebApi.WebApi.wsScoreComportamiento.ELScoreComportamientoDatos poDatos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoreComportamiento/DevuelveScoreComportamiento", ReplyAction="http://tempuri.org/IwsScoreComportamiento/DevuelveScoreComportamientoResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoreComportamiento.ELScoreComportamientoResultado> DevuelveScoreComportamientoAsync(TiboxWebApi.WebApi.wsScoreComportamiento.ELScoreComportamientoDatos poDatos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsScoreComportamientoChannel : TiboxWebApi.WebApi.wsScoreComportamiento.IwsScoreComportamiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsScoreComportamientoClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsScoreComportamiento.IwsScoreComportamiento>, TiboxWebApi.WebApi.wsScoreComportamiento.IwsScoreComportamiento {
        
        public IwsScoreComportamientoClient() {
        }
        
        public IwsScoreComportamientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsScoreComportamientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoreComportamientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoreComportamientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TiboxWebApi.WebApi.wsScoreComportamiento.ELScoreComportamientoResultado DevuelveScoreComportamiento(TiboxWebApi.WebApi.wsScoreComportamiento.ELScoreComportamientoDatos poDatos) {
            return base.Channel.DevuelveScoreComportamiento(poDatos);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoreComportamiento.ELScoreComportamientoResultado> DevuelveScoreComportamientoAsync(TiboxWebApi.WebApi.wsScoreComportamiento.ELScoreComportamientoDatos poDatos) {
            return base.Channel.DevuelveScoreComportamientoAsync(poDatos);
        }
    }
}
