//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSms.wsSMSSoap")]
    public interface wsSMSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Telefono del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarMensaje", ReplyAction="*")]
        TiboxWebApi.WebApi.wsSms.EnviarMensajeResponse EnviarMensaje(TiboxWebApi.WebApi.wsSms.EnviarMensajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarMensaje", ReplyAction="*")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsSms.EnviarMensajeResponse> EnviarMensajeAsync(TiboxWebApi.WebApi.wsSms.EnviarMensajeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarMensajeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarMensaje", Namespace="http://tempuri.org/", Order=0)]
        public TiboxWebApi.WebApi.wsSms.EnviarMensajeRequestBody Body;
        
        public EnviarMensajeRequest() {
        }
        
        public EnviarMensajeRequest(TiboxWebApi.WebApi.wsSms.EnviarMensajeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarMensajeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msg;
        
        public EnviarMensajeRequestBody() {
        }
        
        public EnviarMensajeRequestBody(string Telefono, string Msg) {
            this.Telefono = Telefono;
            this.Msg = Msg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarMensajeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarMensajeResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiboxWebApi.WebApi.wsSms.EnviarMensajeResponseBody Body;
        
        public EnviarMensajeResponse() {
        }
        
        public EnviarMensajeResponse(TiboxWebApi.WebApi.wsSms.EnviarMensajeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarMensajeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EnviarMensajeResult;
        
        public EnviarMensajeResponseBody() {
        }
        
        public EnviarMensajeResponseBody(bool EnviarMensajeResult) {
            this.EnviarMensajeResult = EnviarMensajeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSMSSoapChannel : TiboxWebApi.WebApi.wsSms.wsSMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSMSSoapClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsSms.wsSMSSoap>, TiboxWebApi.WebApi.wsSms.wsSMSSoap {
        
        public wsSMSSoapClient() {
        }
        
        public wsSMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiboxWebApi.WebApi.wsSms.EnviarMensajeResponse TiboxWebApi.WebApi.wsSms.wsSMSSoap.EnviarMensaje(TiboxWebApi.WebApi.wsSms.EnviarMensajeRequest request) {
            return base.Channel.EnviarMensaje(request);
        }
        
        public bool EnviarMensaje(string Telefono, string Msg) {
            TiboxWebApi.WebApi.wsSms.EnviarMensajeRequest inValue = new TiboxWebApi.WebApi.wsSms.EnviarMensajeRequest();
            inValue.Body = new TiboxWebApi.WebApi.wsSms.EnviarMensajeRequestBody();
            inValue.Body.Telefono = Telefono;
            inValue.Body.Msg = Msg;
            TiboxWebApi.WebApi.wsSms.EnviarMensajeResponse retVal = ((TiboxWebApi.WebApi.wsSms.wsSMSSoap)(this)).EnviarMensaje(inValue);
            return retVal.Body.EnviarMensajeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsSms.EnviarMensajeResponse> TiboxWebApi.WebApi.wsSms.wsSMSSoap.EnviarMensajeAsync(TiboxWebApi.WebApi.wsSms.EnviarMensajeRequest request) {
            return base.Channel.EnviarMensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsSms.EnviarMensajeResponse> EnviarMensajeAsync(string Telefono, string Msg) {
            TiboxWebApi.WebApi.wsSms.EnviarMensajeRequest inValue = new TiboxWebApi.WebApi.wsSms.EnviarMensajeRequest();
            inValue.Body = new TiboxWebApi.WebApi.wsSms.EnviarMensajeRequestBody();
            inValue.Body.Telefono = Telefono;
            inValue.Body.Msg = Msg;
            return ((TiboxWebApi.WebApi.wsSms.wsSMSSoap)(this)).EnviarMensajeAsync(inValue);
        }
    }
}
