//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiboxWebApi.WebApi.wsScoreDemografico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoreDemograficoDatos", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoreDemograficoDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nCondicionLaboralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nEdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nEstadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nGeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nIngresoSalarialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nMoraComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nRankingTop10000Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nSituacionLaboralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nViviendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsScoreDemografico.ELDocumento oDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nCondicionLaboral {
            get {
                return this.nCondicionLaboralField;
            }
            set {
                if ((object.ReferenceEquals(this.nCondicionLaboralField, value) != true)) {
                    this.nCondicionLaboralField = value;
                    this.RaisePropertyChanged("nCondicionLaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nDepartamento {
            get {
                return this.nDepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.nDepartamentoField, value) != true)) {
                    this.nDepartamentoField = value;
                    this.RaisePropertyChanged("nDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nEdad {
            get {
                return this.nEdadField;
            }
            set {
                if ((object.ReferenceEquals(this.nEdadField, value) != true)) {
                    this.nEdadField = value;
                    this.RaisePropertyChanged("nEdad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nEstadoCivil {
            get {
                return this.nEstadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.nEstadoCivilField, value) != true)) {
                    this.nEstadoCivilField = value;
                    this.RaisePropertyChanged("nEstadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nGenero {
            get {
                return this.nGeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.nGeneroField, value) != true)) {
                    this.nGeneroField = value;
                    this.RaisePropertyChanged("nGenero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nIngresoSalarial {
            get {
                return this.nIngresoSalarialField;
            }
            set {
                if ((object.ReferenceEquals(this.nIngresoSalarialField, value) != true)) {
                    this.nIngresoSalarialField = value;
                    this.RaisePropertyChanged("nIngresoSalarial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nMoraComercial {
            get {
                return this.nMoraComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.nMoraComercialField, value) != true)) {
                    this.nMoraComercialField = value;
                    this.RaisePropertyChanged("nMoraComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nRankingTop10000 {
            get {
                return this.nRankingTop10000Field;
            }
            set {
                if ((object.ReferenceEquals(this.nRankingTop10000Field, value) != true)) {
                    this.nRankingTop10000Field = value;
                    this.RaisePropertyChanged("nRankingTop10000");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nSituacionLaboral {
            get {
                return this.nSituacionLaboralField;
            }
            set {
                if ((object.ReferenceEquals(this.nSituacionLaboralField, value) != true)) {
                    this.nSituacionLaboralField = value;
                    this.RaisePropertyChanged("nSituacionLaboral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nVivienda {
            get {
                return this.nViviendaField;
            }
            set {
                if ((object.ReferenceEquals(this.nViviendaField, value) != true)) {
                    this.nViviendaField = value;
                    this.RaisePropertyChanged("nVivienda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsScoreDemografico.ELDocumento oDocumento {
            get {
                return this.oDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.oDocumentoField, value) != true)) {
                    this.oDocumentoField = value;
                    this.RaisePropertyChanged("oDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELDocumento", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nTipoDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sNroDocField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nTipoDoc {
            get {
                return this.nTipoDocField;
            }
            set {
                if ((object.ReferenceEquals(this.nTipoDocField, value) != true)) {
                    this.nTipoDocField = value;
                    this.RaisePropertyChanged("nTipoDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sNroDoc {
            get {
                return this.sNroDocField;
            }
            set {
                if ((object.ReferenceEquals(this.sNroDocField, value) != true)) {
                    this.sNroDocField = value;
                    this.RaisePropertyChanged("sNroDoc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ELScoreDemograficoResultado", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ELScoreDemograficoResultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nScoreDemograficoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TiboxWebApi.WebApi.wsScoreDemografico.ScoreItem[] oScoreItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sMensajeErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bError {
            get {
                return this.bErrorField;
            }
            set {
                if ((this.bErrorField.Equals(value) != true)) {
                    this.bErrorField = value;
                    this.RaisePropertyChanged("bError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nScoreDemografico {
            get {
                return this.nScoreDemograficoField;
            }
            set {
                if ((object.ReferenceEquals(this.nScoreDemograficoField, value) != true)) {
                    this.nScoreDemograficoField = value;
                    this.RaisePropertyChanged("nScoreDemografico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TiboxWebApi.WebApi.wsScoreDemografico.ScoreItem[] oScoreItems {
            get {
                return this.oScoreItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.oScoreItemsField, value) != true)) {
                    this.oScoreItemsField = value;
                    this.RaisePropertyChanged("oScoreItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sMensajeError {
            get {
                return this.sMensajeErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.sMensajeErrorField, value) != true)) {
                    this.sMensajeErrorField = value;
                    this.RaisePropertyChanged("sMensajeError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoreItem", Namespace="http://schemas.datacontract.org/2004/07/SoftBox.Scoring.EntityLayer")]
    [System.SerializableAttribute()]
    public partial class ScoreItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nScoreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nScorePuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sScoreDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nScoreId {
            get {
                return this.nScoreIdField;
            }
            set {
                if ((object.ReferenceEquals(this.nScoreIdField, value) != true)) {
                    this.nScoreIdField = value;
                    this.RaisePropertyChanged("nScoreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nScorePuntaje {
            get {
                return this.nScorePuntajeField;
            }
            set {
                if ((object.ReferenceEquals(this.nScorePuntajeField, value) != true)) {
                    this.nScorePuntajeField = value;
                    this.RaisePropertyChanged("nScorePuntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sScore {
            get {
                return this.sScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.sScoreField, value) != true)) {
                    this.sScoreField = value;
                    this.RaisePropertyChanged("sScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sScoreDescripcion {
            get {
                return this.sScoreDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.sScoreDescripcionField, value) != true)) {
                    this.sScoreDescripcionField = value;
                    this.RaisePropertyChanged("sScoreDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsScoreDemografico.IwsScoreDemografico")]
    public interface IwsScoreDemografico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoreDemografico/ScoreDemografico", ReplyAction="http://tempuri.org/IwsScoreDemografico/ScoreDemograficoResponse")]
        TiboxWebApi.WebApi.wsScoreDemografico.ELScoreDemograficoResultado ScoreDemografico(TiboxWebApi.WebApi.wsScoreDemografico.ELScoreDemograficoDatos poDatosScore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoreDemografico/ScoreDemografico", ReplyAction="http://tempuri.org/IwsScoreDemografico/ScoreDemograficoResponse")]
        System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoreDemografico.ELScoreDemograficoResultado> ScoreDemograficoAsync(TiboxWebApi.WebApi.wsScoreDemografico.ELScoreDemograficoDatos poDatosScore);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoreDemografico/DevuelveMoraComercial", ReplyAction="http://tempuri.org/IwsScoreDemografico/DevuelveMoraComercialResponse")]
        double DevuelveMoraComercial(TiboxWebApi.WebApi.wsScoreDemografico.ELDocumento poDatosPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsScoreDemografico/DevuelveMoraComercial", ReplyAction="http://tempuri.org/IwsScoreDemografico/DevuelveMoraComercialResponse")]
        System.Threading.Tasks.Task<double> DevuelveMoraComercialAsync(TiboxWebApi.WebApi.wsScoreDemografico.ELDocumento poDatosPersona);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IwsScoreDemograficoChannel : TiboxWebApi.WebApi.wsScoreDemografico.IwsScoreDemografico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IwsScoreDemograficoClient : System.ServiceModel.ClientBase<TiboxWebApi.WebApi.wsScoreDemografico.IwsScoreDemografico>, TiboxWebApi.WebApi.wsScoreDemografico.IwsScoreDemografico {
        
        public IwsScoreDemograficoClient() {
        }
        
        public IwsScoreDemograficoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IwsScoreDemograficoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoreDemograficoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IwsScoreDemograficoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TiboxWebApi.WebApi.wsScoreDemografico.ELScoreDemograficoResultado ScoreDemografico(TiboxWebApi.WebApi.wsScoreDemografico.ELScoreDemograficoDatos poDatosScore) {
            return base.Channel.ScoreDemografico(poDatosScore);
        }
        
        public System.Threading.Tasks.Task<TiboxWebApi.WebApi.wsScoreDemografico.ELScoreDemograficoResultado> ScoreDemograficoAsync(TiboxWebApi.WebApi.wsScoreDemografico.ELScoreDemograficoDatos poDatosScore) {
            return base.Channel.ScoreDemograficoAsync(poDatosScore);
        }
        
        public double DevuelveMoraComercial(TiboxWebApi.WebApi.wsScoreDemografico.ELDocumento poDatosPersona) {
            return base.Channel.DevuelveMoraComercial(poDatosPersona);
        }
        
        public System.Threading.Tasks.Task<double> DevuelveMoraComercialAsync(TiboxWebApi.WebApi.wsScoreDemografico.ELDocumento poDatosPersona) {
            return base.Channel.DevuelveMoraComercialAsync(poDatosPersona);
        }
    }
}
